name: Deploy Logger Service

on:
  push:
    branches:
      - main  # Событие для ветки main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем код
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      # Шаг 4: Собираем бандл
      - name: Build project
        run: node esbuild.js

      # Шаг 5: Загружаем бандл на сервер
      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: './shared/logger/app.js'
          target: '/shared/logger/app.js'

      # Шаг 6: Перезапускаем сервис на сервере
      - name: Restart logger service
        run: ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "sudo systemctl restart gs_service-logger"